### ISSUE TITLE
Slow load when shown from an on tap event /w scroll enabled

### ISSUE THREAD

**Issue by dorthwein** [christopherdro/react-native-calendar#10]
There is a long pause when the cal is shown as a result of a state change after the initial render.  This seems to only be an issue when scroll is enabled.

If anyone has any suggestions or direction on this i'd be happy to work on it and do a pull request.

**Comment by dorthwein** [comment]
This issue also seems to occur if the rendered cal is moved in any way.

**Comment by coderdave** [comment]
Are you using the latest 0.5.0? We made a few performance changes in that release and is a lot snappier.

**Comment by dorthwein** [comment]
@coderdave - Yep - using version 0.5.0

**Comment by coderdave** [comment]
Ok, I'm not seeing a long pause when scroll is enabled or disabled. Are you able to provide a code sample?

**Comment by dorthwein** [comment]
We're changing how we use this - let me get back to you after the redo.  Thanks for the prompt response!

**Comment by dorthwein** [comment]
It has something to do with showing it and re-rendering the cal after its been torn down.

**Comment by coderdave** [comment]
Has this been resolved?

**Comment by vtam311** [comment]
I'm running into this same issue now. Disabling the scroll does make this render more quickly, but once it's enabled, the page takes quite a while to load. 

@dorthwein have you resolved this?

**Comment by dorthwein** [comment]
@waterdoo no sorry - I switched to date spinners ;(

**Comment by vtam311** [comment]
Ah I see, well thanks for the response anyway. @coderdave if you're still interested in looking at the code to understand this, I'd be happy to share.

**Comment by coderdave** [comment]
I'm actually using date spinners instead of scrolling inside my app too because I need to load data.
@waterdoo if you turn off chrome debugging, is it still slow? I've seen that before.

**Comment by georgelam0306** [comment]
Picking on the calendar seems to be very slow when I run it on iphone 5 and down for me.
