### ISSUE TITLE
Showing only months and year

### ISSUE THREAD

**Issue by Akshay9882** [christopherdro/react-native-calendar#101]
Is it possible to modify this calendar to shown only months and year, i want to modify it to show only months and years like below view
```
<     2017           >
   Jan   Feb    Mar
   Apr   May    Jun
   Jul   Aug    Sep 
   Oct   Nov    Dec
```

**Comment by christopherdro** [comment]
Hi @Akshay9882. Unfortunately the this library does not provide this out of the box.

You'll be better off just making a simple component yourself for this.
