### ISSUE TITLE
Jump to current date

### ISSUE THREAD

**Issue by junedomingo** [christopherdro/react-native-calendar#104]
After swiping through months, how can i jump back to current date?

**Comment by christopherdro** [comment]
You can set a ref on the calendar component and use `scrollToItem`
https://github.com/christopherdro/react-native-calendar/blob/e8da5b74c47079c5e591313e95745edbaf6104c5/components/Calendar.js#L148

**Comment by jankcat** [comment]
What if we don't have scrollEnabled, and don't want to enable it?

Edit: found [selectDate(date)](https://github.com/christopherdro/react-native-calendar/blob/master/components/Calendar.js#L134), just need to find a way to go back to that month as well

**Comment by junedomingo** [comment]
Thanks @christopherdro .

Good question @jankcat , actually i also disabled the scrolling capability because of a bit lag.
