### ISSUE TITLE
[Bug] Next and Prev buttons do not display

### ISSUE THREAD

**Issue by ithieund** [christopherdro/react-native-calendar#108]
@christopherdro ,
I'm so happy seeing this plugin, it is an alternative and better than react-native-calendar-picker.
But when I try this, the Prev and Next button do not display in my emulator.
Beside that, the layout seems not correct as it leave a large blank at the bottom.
Sometime that blank scrolled up when swiping into the another month, but sometime it scrolled down event if there is no date in that line.

<img width="620" alt="screenshot at mar 08 18-24-44" src="https://cloud.githubusercontent.com/assets/4217195/23702200/dc19bd38-042c-11e7-9980-c3e4d6cf55e3.png">

Can you please fix that soon?
Thanks.

**Comment by ithieund** [comment]
Hi @christopherdro ,
Sorry I was missing the prop showControls.
The Prev and Next buttons showed now.

But: 
1. The issue about the calendar height still exist.
2. When the control buttons are showed, the prop titleFormat does not affected any more. I looked into your code, 
the line 262 is: {localizedMonth} {this.state.currentMonthMoment.year()} 
it should be: {this.state.currentMonthMoment.format(this.props.titleFormat)}

Please fix them soon.
Thanks.

**Comment by ithieund** [comment]
@coderdave ,
Can you please see this.

Thanks.

**Comment by christopherdro** [comment]
This has already been merged via https://github.com/christopherdro/react-native-calendar/commit/aeb299e32c796e589ff97c1e598dfa1d045d2f5d

New release coming soon.

**Comment by ithieund** [comment]
@christopherdro ,
Thanks.
