### ISSUE TITLE
Custom day renderer

### ISSUE THREAD

**Issue by carera** [christopherdro/react-native-calendar#109]
Hi, do you think it is somehow possible to provide the `Calendar` component a custom rendering function to render `Day`? What are we looking for is to render multiple information within a single day. Something along the lines of

![image](https://cloud.githubusercontent.com/assets/1365752/23744589/1ee51328-04b5-11e7-95a8-b0b215b28889.png)

Thanks

**Comment by christopherdro** [comment]
@carera You might be better off forking this repo and making the custom adjustments you need to.

**Comment by Kumar-River** [comment]
Hi,

I am also looking for the same kind of Calendar component like adding multiple event indicators for a day with different colors. Is there any working progress on this?

**Comment by luisfuertes** [comment]
Some components like [react-native-gifted-chat](https://github.com/FaridSafi/react-native-gifted-chat) give this option like:

``` 
import {Calendar, Day} from 'react-native-calendar' 

renderDay(props) {
    return (
      <Day
        {...props}
        text={'day text}
        events={eventsArray}
        />
    )
}

render() {
 return (
  <Calendar
    renderDay={this.renderDay.bind(this)}
  />
 )
}
``` 

That would be great.

**Comment by lavarajallu** [comment]
If I am Clicking On Some Particular Date ,how can I Displayed That Date Day Name and Day ID Can you suggest for me
