### ISSUE TITLE
Month text doesn't changed with scrollEnabled={false} 

### ISSUE THREAD

**Issue by Intellicode** [christopherdro/react-native-calendar#11]
When I use `scrollEnabled={false}` and I press next or previous, the month text doesn't change. I'll probably make a PR for this when I fixed it.

**Comment by coderdave** [comment]
![calendar](https://cloud.githubusercontent.com/assets/964751/10559777/e2ab1aae-74c5-11e5-983f-ef9c38f101ec.gif)

Looks like the month text is changing.

**Comment by christopherdro** [comment]
@coderdave I think he meant when scrollEnabled is false and he is using the buttons to navigate

**Comment by Intellicode** [comment]
Indeed, when swiping (and thus have scrolling enabled) it works fine. I already fixed this in our fork, but I'll make a PR for it so it will be fixed in the original version as well.

**Comment by christopherdro** [comment]
:+1:

**Comment by coderdave** [comment]
Sorry, totally misread that!
