### ISSUE TITLE
[Feature Request] Get current display month and year

### ISSUE THREAD

**Issue by ithieund** [christopherdro/react-native-calendar#110]
Hi @christopherdro  and @coderdave ,
Can you please provide an api to get the current month and year that is displaying.
Currently the selected date is not related to the display month after swiping or touching the control button so this API is needed.

Another approach that does not need to provide api is to automatically select the appropriate date in the display month, the plugin react-native-date-picker already have this feature.

Looking forward to your feedback.
Thanks.

**Comment by christopherdro** [comment]
Hey there.
You can easily do this yourself by using the date returned in the callbacks for swipe or touch.

**Comment by ithieund** [comment]
@christopherdro ,
I'll try.

Thanks.
