### ISSUE TITLE
enabling scrollEnabled causes app to crash

### ISSUE THREAD

**Issue by Treybro** [christopherdro/react-native-calendar#112]
Hey all!

After enabling scrollEnabled={true} within my Calendar component, my app now crashes with the following error

> null is not an object (evaluating 'this._calendar.scrollTo')

This is currently my Calendar implementation.

```
<Calendar
 ref="calendar"
 eventDates={this.props.eventDates}
 showControls={true}
 showEventIndicators={true}
 customStyle={customCalandarStyle}
 scrollEnabled/>
```

Am I missing something here?

Thank you.

**Comment by Treybro** [comment]
Figured it out, I had an if statement which determines if the Calendar is rendered or not - the switch was happening so fast the Calendar child components we're not catching up so the reference was gone.

**Comment by coderdave** [comment]
@Treybro Thank you for clueing me in on the problem! I was also conditionally showing the calendar and if I switched to a view quick enough that doesn't have the calendar, I got this error.

So I just committed (https://github.com/christopherdro/react-native-calendar/commit/af3d38e08a0e16f7a1b4217c7948cf837916c58b) a simple check to make sure `this._calendar` is defined before calling `scrollTo`.
