### ISSUE TITLE
Can i Add more Details below calender  i want Design more...

### ISSUE THREAD

**Issue by lavarajallu** [christopherdro/react-native-calendar#118]
Actually i used this calender, but i have a Displayed calender i want design below page .. When i was Design extra part it's not showing Design part.. Can you tell me any other way to Design Calender Below

**Comment by christopherdro** [comment]
Not sure I quite understand. Do you mean styling the calendar in general?

Any chance you already saw https://github.com/christopherdro/react-native-calendar#available-custom-styles?

**Comment by lavarajallu** [comment]
no no not like that.... I want like this how can i Designed...
![manage address](https://cloud.githubusercontent.com/assets/20550556/24132885/c9ac4a98-0e1e-11e7-9f8b-9a59a33ee072.png)

**Comment by christopherdro** [comment]
@lavarajallu I'm sorry but I am going to close out this issue since it's not a bug in the library. Stackoverflow might be a better options here.
