### ISSUE TITLE
Sometimes crash on first render

### ISSUE THREAD

**Issue by ithieund** [christopherdro/react-native-calendar#119]
@christopherdro ,
I'm facing with this issue several times, it just crash the app in Emulator and shows 'Unfortunately app has stopped'.

This is all what I have in the log:
> --------- beginning of crash

This is my code

> <EventCalendar
>                                 titleFormat='[Tháng] MM / YYYY'
>                                 selectedDate={this.state.date}
>                                 onDateSelect={this.onDateChange.bind(this)}
>                                 showControls={true}
>                                 dayHeadings={['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7']}
>                                 eventDates={this.state.eventDates}
>                                 prevButtonText={'❮'}
>                                 nextButtonText={'❯'}
>                                 scrollEnabled={true}
>                                 weekStart={1}
>                                 selectedDayColor='#00c497'
>                                 customStyle={calendarStyle}
>                             />

Please check and fix it.
Thanks.

**Comment by christopherdro** [comment]
How are you sure it's related to this library?

**Comment by ithieund** [comment]
@christopherdro ,
It was working fine with react-native-calendar-picker previously.
I just got the date return from the lib and call http fetch.

After replacing that lib with this lib, some times it crash without any log. It crash before http fetch request started.
It's just sometimes, not always so I posted here to see if someone has the same issue.

I'm appreciate if you could take a look with this.
Thanks.

**Comment by christopherdro** [comment]
It's gonna be difficult to track a crash down with no error reporting. I'm gonna assume it's something with your application since their would've been more reports of crashing was hapening from this library.

**Comment by ithieund** [comment]
@christopherdro ,
Thank you very much for your feedback.
Until now, this issue is only happen in emulators, the app running in physical device is OK. It's enough for me currently :)

Thanks.
