### ISSUE TITLE
question: How to add date to calendar

### ISSUE THREAD

**Issue by alesanabriav7** [christopherdro/react-native-calendar#12]
Hi, I try to make a link but i don't find any documentation about that, someone knows how to make a link to add date to calendar app? thanks y'all.

**Comment by christopherdro** [comment]
@developersoul Are you referring to adding a date to the native calendar app or adding a specific event to this calendar module?

**Comment by alesanabriav7** [comment]
Add to calendar app

**Comment by christopherdro** [comment]
Unfortunately this module doesn't support that. Going to need native support for this to work.
There is actually a good example in the docs. https://facebook.github.io/react-native/docs/native-modules-ios.html#ios-calendar-module-example

If you think this is something you can work and possibly submit a PR, that would be great :)
