### ISSUE TITLE
titleFormat does not affect when showControls is true

### ISSUE THREAD

**Issue by ithieund** [christopherdro/react-native-calendar#122]
@christopherdro ,
Can you please check this case?
I saw your code look OK but this case is not work. It still show the default titleFormat, not what I passed in.

Thanks.

**Comment by Mad-hu** [comment]
Solved? @ithieund

**Comment by christopherdro** [comment]
Fixed via https://github.com/christopherdro/react-native-calendar/commit/9dae00d84aae28d5289e099eebf6fe41c0f93733
