### ISSUE TITLE
weekendDayButton not working

### ISSUE THREAD

**Issue by jmdelatorre** [christopherdro/react-native-calendar#136]
Hi,

im trying to set a background to my calendar but weekendDayButton is not working

my customStyle is
`const customStyle = {
  weekendDayButton: {
    backgroundColor: '#2980b9'
  },
  calendarContainer: {
    backgroundColor: '#2980b9'
  },
};`
<img width="373" alt="screenshot 2017-05-14 23 41 10" src="https://cloud.githubusercontent.com/assets/10604162/26041914/d365a39e-38fe-11e7-998b-0532836ec034.png">

help?

**Comment by x-bingxin** [comment]
Same issue +1

**Comment by x-bingxin** [comment]
@jmdelatorre I checked that `customStyle.weekendDayButton` was missed to append in line 89 of file Day.js, hope this will be correct soon.

**Comment by christopherdro** [comment]
Sorry for the delay. https://github.com/christopherdro/react-native-calendar/releases/tag/v0.12.3
