### ISSUE TITLE
Crashing onLongPress for Day

### ISSUE THREAD

**Issue by nolan-m** [christopherdro/react-native-calendar#144]
Library will crash app if user attempts long press on day.

Looks like the Calendar component is passing a onLongPress function into Day, but this.longPress is no defined anywhere in Calendar.js

**Comment by nolan-m** [comment]
I see there is a PR for fixing this.

https://github.com/christopherdro/react-native-calendar/pull/134

**Comment by christopherdro** [comment]
https://github.com/christopherdro/react-native-calendar/pull/158
