### ISSUE TITLE
Custom month names don't seem to work

### ISSUE THREAD

**Issue by newah** [christopherdro/react-native-calendar#149]
in Calendar.js

renderTopBar() {
    let localizedMonth = this.props.monthNames[this.state.currentMonthMoment.month()];

localizedMonth variable is created, but not used.

Or maybe I'm missing something?

**Comment by christopherdro** [comment]
@newah What version are you in?

I believe your running into a bug from an older version that was resolved via https://github.com/christopherdro/react-native-calendar/commit/9dae00d84aae28d5289e099eebf6fe41c0f93733

**Comment by newah** [comment]
@christopherdro from the code I see it was fixed in newer version, thanks!
I was on 0.11.0
