### ISSUE TITLE
C++ Exception in 'nativeFlushQueueImmediate'

### ISSUE THREAD

**Issue by baudev** [christopherdro/react-native-calendar#152]
Since the last update, I have the following problem : 
 ```
C++ Exception in 'nativeFlushQueueImmediate': Exception creating JSON string: RangeError: Maximum call stack size exceeded.
```

Is it due to this update or an isolate case ? 
react-native-calendar v0.12.3

**EDIT**
Just stupid error from me, sorry. You can delete this issue.

**Comment by raunaqss** [comment]
@baudev 

I'm getting a similar error and am having trouble debugging the same. Could you please tell me more about what caused the error in your case?
