### ISSUE TITLE
Warning: PropTypes has been moved

### ISSUE THREAD

**Issue by hszeto** [christopherdro/react-native-calendar#167]
I'm getting the following warning in the console.

```Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.```

How can I fix it?  

I'm running:
```
"react-native": "0.46.4",
"react": "16.0.0-alpha.12",
"react-native-calendar": "^0.12.3",
```

**Comment by bradbyte** [comment]
This is causing my app to crash when attempting to update to RN 49.
