### ISSUE TITLE
Days (numbers) not in line with days of the week header when using margin

### ISSUE THREAD

**Issue by nbastoWM** [christopherdro/react-native-calendar#17]
Hi,
I'm using the iPhone 5 simulator and the days are not aligned with the days of the week. The header shows fine, but the last column of days (numbers) shows just half. I've tryed to reduce the size of the day font but it's the same.

Another problem I'm facing is, everytime I press one day, the calendar scrolls to the previous month.

Regards.

**Comment by coderdave** [comment]
Can you send a screenshot?

**Comment by coderdave** [comment]
Haven't heard anything back.

**Comment by irfanayaz89** [comment]
@nbastoWM Did you find a solution? I am facing the same issue.

**Comment by irfanayaz89** [comment]
@coderdave This happens when the calendar is inside a view with margin. Any solution for this?
<img width="331" alt="screen shot 2017-02-10 at 4 54 41 pm" src="https://cloud.githubusercontent.com/assets/19551207/22825916/8977519c-efb1-11e6-806e-1ffda6056cab.png">

**Comment by coderdave** [comment]
I do see this problem now. It's because we rely on this line: https://github.com/christopherdro/react-native-calendar/blob/master/components/Calendar.js#L15 to determine the width of the calendar.

There is a `width` property that is exposed, but with the little time I played with it, it didn't yield good results. Maybe for you?

**Comment by irfanayaz89** [comment]
I had to do a workaround to get it working. Got the width of the device from Dimensions and subtracted my margins from that width and supplied that to the width property. Also had to set month container width to the same and dayButton and dayButton filler to that/7
