### ISSUE TITLE
CustomStyle

### ISSUE THREAD

**Issue by leedanieljk** [christopherdro/react-native-calendar#20]
Hey there,

First off, thank you for uploading the calendar for every to use its awesome.

I was trying to change the style of the calendar using the syntax that you posted on your page, but it seems not to be working. 

For example, to change the currentDayCircle I used this code but it would not work. 

  <Calendar
          style={{flex: 0.7}}
          ref="calendar"
          showControls={true}
          titleFormat={'MMMM YYYY'}
          prevButtonText={'<'}
          nextButtonText={'>'}
          onDateSelect={this.handleDatePress}
          customStyle={{currentDayCircle: {backgroundColor : 'blue' }}}/>

I was wondering if this was a bug? Thank you for your help.

**Comment by coderdave** [comment]
That should work.

``` javascript
        <Calendar
          scrollEnabled={false}
          showControls={true}
          dayHeadings={['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']}
          onTouchPrev={this.onTouchPrev}
          onTouchNext={this.onTouchNext}
          onSwipeNext={this.onSwipeNext}
          onSwipePrev={this.onSwipePrev}
          onDateSelect={this.onDateSelect}
          eventDates={eventDates}
          startDate={this.state.start}
          customStyle={{currentDayCircle: {backgroundColor: 'blue'}}}
          selectedDate={this.state.selectedDate}
         />
```
