### ISSUE TITLE
Unable to resolve module from moment

### ISSUE THREAD

**Issue by Sir-Chasington** [christopherdro/react-native-calendar#24]
After trying to test this calendar module I replaced the index.ios.js with the example, I get and error in the simulator "Unable to resolve module moment from ... Unable to find this module in its module map or any of the node_modules directories under ... and its parent directories. "

It gave a suggestion to fix but I tried and still get this issue. Any clue what the issue might be?

**Comment by coderdave** [comment]
You added react-native-calendar to your package?

**Comment by kosmaks** [comment]
I'm having same issue with 0.6.3. Looks like there's no CalendarIOS.js under node_modules. 0.6.2 works fine.

**Comment by kapilsipl** [comment]
It's showing dependency error, please use below command to resolve-
rm -rf node_modules && npm install

**Comment by ishara28** [comment]
what mean by "-rf". I couldn't run with -rf.

**Comment by kapilsipl** [comment]
> what mean by "-rf". I couldn't run with -rf.

try 
rimraf node_modules && npm install
If you don't have rimraf, just install by below command
npm install rimraf -g
