### ISSUE TITLE
Week View

### ISSUE THREAD

**Issue by jedt** [christopherdro/react-native-calendar#28]
Not an issue but more of a friendly tip. 

My fork has a week view. It's not perfect but it works. I am able to switch to week and month view. If anyone would want this as an option let me know, I'll try to submit it as a PR.

![alt text](http://i.imgur.com/04JjrsD.png?1)

https://github.com/jedt/react-native-calendar/blob/master/CalendarIOS.js#L231-L273

**Comment by brianinator** [comment]
Excellent work! I have a need for this as well. Looks good.

**Comment by devekoperiOS** [comment]
For me, renderHeading gives me error which is "this.props.dayHeadings.map"  is not a function. And If I keep that lines in comment, then it displays calendar without week days.

**Comment by joshjhargreaves** [comment]
Would love to see this as well :)

**Comment by brianinator** [comment]
It's been a while. @jedt Do you need help with that warning?

**Comment by joshjhargreaves** [comment]
+1
