### ISSUE TITLE
Feature request: Customizable start date

### ISSUE THREAD

**Issue by PhilippKrone** [christopherdro/react-native-calendar#3]
Hi,

yet another feature request: the current calendar sesms to start with "Sun" all the time. It'd be nice if one is able to customize the starting date, i.e. having "Monday" at the very left of the calendar.

Regards
Philipp

**Comment by christopherdro** [comment]
I think the standard is to start the week on Sunday. Actually, this is how the javascript handles date objects where Sunday gets the value of '0'.

What your requesting is doable but I think it might be an edge case. 

Feel free to fork the project, make your adjustments and use that for your project.

**Comment by PhilippKrone** [comment]
Hi,

indeed from a javascript and US respective, it's the standard to start with Sunday. I'm gonna make it dynamical in my fork and try to provide a PR afterwards.

Regards
Philipp

**Comment by christopherdro** [comment]
Sorry, was just looking into it. Your right :) 
Most european countries have Monday as the start of the week.

Checkout http://momentjs.com/docs/#/i18n/

As you can see from the locale files we can actually retrieve a lot of info that we can plugin into the calendar. This would be ideal. 

This was going to be my approach for adding language support.

Maybe you can try figuring it out using this? This would really help integrating other language features moving forward.

Thanks!

**Comment by PhilippKrone** [comment]
Hi,

yeah, I'm already taking a look at that, but had my issues with multi language support using moment at react-native before.. :) Gonna give it a try this night.

Regards
Philipp

**Comment by christopherdro** [comment]
Any progress?

**Comment by coderdave** [comment]
This is related so I'll post here. I need a start_date also because I'm fetching in "events" for each day from a remote call. So I needed it to go to a loading state before going to the next or previous month, then when the call is complete, start the calendar at that month.

I already have a branch for it where you can pass in `start_date`, but it only changes the MONTH, does not change the day at which to start. But I was thinking you could piggy back off of that to get it start on a certain day. Let me know if this would help and I'll put in a PR.

**Comment by christopherdro** [comment]
You can use the `weekStart` prop to specify this now. Will be available in the next release.

**Comment by Andreyco** [comment]
Looks like `weekStart` is still ignored, correct?

**Comment by christopherdro** [comment]
@Andreyco I haven't pushed a new release with this feature. You can try pulling from master.

I was waiting on getting a few more features for the next release but either way I might end up doing a new one this weekend since a lot has changed.

**Comment by Andreyco** [comment]
Get it. Regarding batching updates into larger releases... I (and I believe most of us) don't mind updating more often :)
