### ISSUE TITLE
Ability to overwrite styles

### ISSUE THREAD

**Issue by andpor** [christopherdro/react-native-calendar#30]
Would be great to have ability to overwrite various style to customize the control to the L&F of the app. border colors, fonts, highlight colors etc.

**Comment by andykuo** [comment]
You can customize the styles by setting the `customStyle` prop.

```
<Calendar
  ...
  customStyle={{day: {fontSize: 15, textAlign: 'center'}}} // Customize any pre-defined styles
/>
```

The styles that are available for customization are in `CalendarIOS.js`

**Comment by coderdave** [comment]
Thank you @andykuo
