### ISSUE TITLE
Unable to resolve module react-native-calendar

### ISSUE THREAD

**Issue by andykuo** [christopherdro/react-native-calendar#31]
After upgrading to version 0.6.3, I'm seeing the following error:

`Unable to resolve module react-native-calendar`

When I look in `node_modules/react-native-calendar`, I don't see `CalendarIOS.js`
Finally, if you try running [https://tonicdev.com/npm/react-native-calendar](url), it says

`Error: Cannot find module 'react-native-calendar'`

Any thoughts?

**Comment by coderdave** [comment]
I just released `0.6.4`, try that one instead.

**Comment by andykuo** [comment]
awesome, that did the trick. thanks!
