### ISSUE TITLE
Support other object type as Controls such as Icon

### ISSUE THREAD

**Issue by 7kfpun** [christopherdro/react-native-calendar#32]
<img width="374" alt="screen shot 2016-05-25 at 1 31 58 am" src="https://cloud.githubusercontent.com/assets/2672802/15513824/d7802088-2218-11e6-9492-1ea451578853.png">

<img width="373" alt="screen shot 2016-05-25 at 1 37 43 am" src="https://cloud.githubusercontent.com/assets/2672802/15513940/4e2add5e-2219-11e6-9f5f-dd4a90842f3c.png">

Hi @christopherdro ,

What do you think?

**Comment by christopherdro** [comment]
@7kfpun I think that is a good feature to have.

I'm planning on redoing this component sometime soon and will allow the previous/next buttons to just take in any component. That way you can deicide if you want to use a `<Text>` or `<Image>` component.
