### ISSUE TITLE
Recent change makes calendar and day react components rather than react-native components

### ISSUE THREAD

**Issue by shuzhang** [christopherdro/react-native-calendar#33]
reference: https://github.com/christopherdro/react-native-calendar/commit/19e543523ceeab0a0756a2b018e4b9dbab1080d0

Specifically:

-let React = require('react-native');
+let React = require('react');
...
let Day = React.createClass({
...
let Calendar = React.createClass({

React components don't always play well with react native components. For a project I'm working on, this was a breaking change for us that ended up being very difficult to track down.

**Comment by coderdave** [comment]
Can you please elaborate on the error that you were seeing?

**Comment by Rmannn** [comment]
You can't import anymore React form react-native package. (BC change in 0.26)
Please require the React from react !
Thx
