### ISSUE TITLE
Remove the last table-row if it's not being used?

### ISSUE THREAD

**Issue by davidfloegel** [christopherdro/react-native-calendar#40]
Hey!

Loving the calendar and using it in an app I'm working on atm.

I was just wondering if it's possible somehow to get rid of the very last table row if it's not being used?
This would enable me to push the content up a little more on some months and not to have a gap there.

I have attached a screenshot!

Thanks
David
![screen shot 2016-06-21 at 14 41 03](https://cloud.githubusercontent.com/assets/13220692/16231535/87770226-37be-11e6-8eb9-c7fc81a97975.png)

**Comment by christopherdro** [comment]
Hmm I'm not sure why its doing that. There is no row there when I use the element inspector.

I'll have to dig in when I get some more time.
@coderdave Any ideas?

**Comment by coderdave** [comment]
Does it go away if you set `scrollEnabled` to `false`?

**Comment by hyb175** [comment]
It is because that at least one of the months in the scrollview has 6 rows and the scrollview needs to have height of 6 rows instead of 5 rows to make sure it can contain that month.
