### ISSUE TITLE
When trying an example and selecting a date: Warning: setState(...): Can only update a mounted or mounting component... 

### ISSUE THREAD

**Issue by kakbeya** [christopherdro/react-native-calendar#41]
Hi,

It looks like I can't make a use of the date selected because of this issue.
Please advise. 

Thanks,
Alex

Code: 

`<Calendar
          ref="calendar"
          eventDates={['2016-07-03', '2016-07-05', '2016-07-28', '2016-07-30']}
          scrollEnabled
          showControls
          dayHeadings={customDayHeadings}
          monthNames={customMonthNames}
          titleFormat={'MMMM YYYY'}
          prevButtonText={'Prev'}
          nextButtonText={'Next'}
          onDateSelect={(date) => this.setState({ selectedDate: date })}
          onTouchPrev={() => console.log('Back TOUCH')}     // eslint-disable-line no-console
          onTouchNext={() => console.log('Forward TOUCH')}  // eslint-disable-line no-console
          onSwipePrev={() => console.log('Back SWIPE')}     // eslint-disable-line no-console
          onSwipeNext={() => console.log('Forward SWIPE')}  // eslint-disable-line no-console
        />
        <Text>Selected Date: {moment(this.state.selectedDate).format('MMMM DD YYYY')}</Text>`

<img width="341" alt="screen shot 2016-06-21 at 4 47 29 pm" src="https://cloud.githubusercontent.com/assets/3266520/16245707/1dd5c91c-37d0-11e6-96eb-77f2c9257cd7.png">

**Comment by coderdave** [comment]
Is `<Calendar>` in a react class with state? If so, can you paste your react class code?

**Comment by kakbeya** [comment]
Yes, it is. Here is the code:

`
export let SelectDate = React.createClass({

```
getInitialState: function () {
    return {
        "selectedDate": moment().format()
    }
},

render: function () {
    return (
        <View style={{flex: 1}}>

            <Calendar
              ref="calendar"
              eventDates={['2016-07-03', '2016-07-05', '2016-07-28', '2016-07-30']}
              scrollEnabled
              showControls
              dayHeadings={customDayHeadings}
              monthNames={customMonthNames}
              titleFormat={'MMMM YYYY'}
              prevButtonText={'Prev'}
              nextButtonText={'Next'}
              onDateSelect={(date) => this.setState({ selectedDate: date })}
              onTouchPrev={() => console.log('Back TOUCH')}     // eslint-disable-line no-console
              onTouchNext={() => console.log('Forward TOUCH')}  // eslint-disable-line no-console
              onSwipePrev={() => console.log('Back SWIPE')}     // eslint-disable-line no-console
              onSwipeNext={() => console.log('Forward SWIPE')}  // eslint-disable-line no-console
            />
            <Text>Selected Date: {moment(this.state.selectedDate).format('MMMM DD YYYY')}</Text>

        </View>
    );
}
```

});
`

**Comment by christopherdro** [comment]
Are you setting state anywhere else ?

**Comment by kakbeya** [comment]
Nope, just wanted to try this example. Running on react-native 0.24.1 together with react-native-router-flux

**Comment by christopherdro** [comment]
Ah yea, I have to update the example. I think this warning shows if any setState happens within render.

Try changing  
`onDateSelect={(date) => this.setState({ selectedDate: date })}` 
to
 `onDateSelect={this.setDate}`

and add the following within the component

```
setDate(selectedDate) {
  this.setState({selectedDate});
}
```

**Comment by kakbeya** [comment]
Thanks, I tried that and other variations, but no luck. Same warning...

**Comment by kakbeya** [comment]
The issue was not related to this module, closing it. Thank you for help!
