### ISSUE TITLE
Event indicators are not showing on the first render of the calendar on android

### ISSUE THREAD

**Issue by pspeake87** [christopherdro/react-native-calendar#48]
I dont know if android is actively being supported yet but the calendar appears to work well on android except the event indicators are not showing on the calendar until you select a date or change the month

**Comment by christopherdro** [comment]
How are you retrieving your events?

Can you log and make sure those are available on initial render?

**Comment by RazorBach** [comment]
Same Problem.Event will not show until I select a date.And when I change the month the first time,it acts like that I was in May but not July.

**Comment by vincentfretin** [comment]
I guess it's the same issue as #43 that you should reopen there.
