### ISSUE TITLE
Not able to set width to 1/3 device width for example

### ISSUE THREAD

**Issue by pavlelekic** [christopherdro/react-native-calendar#49]
Hi,
First, thanks for the great calendar, it really looks nice, has a lot of features. The one problem I have is I'm trying to use it on ipad inside the popover, so it shouldn't be full width, the popover is not so big it should be probably 1/3 of device width. I have problems setting custom width, the top header and buttons look ok but the cells for days are too wide, it looks like they are made to fit calendar in full width (device width). Is there a way to set a custom width of a calendar and have day cells look as they should?

Thanks.

**Comment by christopherdro** [comment]
Hey @pavlelekic What version are you using?

There was a option adding for this in 0.7.0.

**Comment by pavlelekic** [comment]
Thanks for the quick reply, I'm using 0.7.0. So it is possible to shrink the calendar width to 1/3 screen width? I've tried with customStyle={{day: {width: 50}}} but it doesn't seem to work the way I want to. Maybe I'm doing something wrong?

**Comment by christopherdro** [comment]
Take a look at custom styles `calendarContainer` and `monthContainer`
https://github.com/christopherdro/react-native-calendar#available-custom-styles

**Comment by devanymoe** [comment]
The calendar width can be customized by setting widths on monthContainer, dayButton, and dayButtonFiller. However, once the calendar width is smaller, the scroll width is off when moving between months. I fixed this on my fork by creating a "width" attribute on the component, which updates the width values in the scrollToItem and scrollEnded functions.
https://github.com/devanymoe/react-native-calendar/commit/a708f7f91fb73da94e081fc3af495a8aac8389e2

```
monthContainer: {width: CALWIDTH},
dayButton: {width: CALWIDTH / 7},
dayButtonFiller: {width: CALWIDTH / 7}
```

**Comment by pavlelekic** [comment]
@devanymoe that's great, thanks! Btw, I think this is really useful, anyone on iPad will want to set custom size for width, since fullscreen width especially in landscape mode is really big. Maybe making a pull request for this is a good idea?

**Comment by christopherdro** [comment]
https://github.com/christopherdro/react-native-calendar/pull/51
