### ISSUE TITLE
Feature Request: when switch month, need to update selectDate

### ISSUE THREAD

**Issue by ghost** [christopherdro/react-native-calendar#52]

**Comment by Andreyco** [comment]
Well... you have full control over this. Listen to `onSwipeNext/onSwipePrev` events. When your callback is invoked, subtract or add a "month" to selected date. Nothing more...

**Comment by ghost** [comment]
@Andreyco  But Calendar ui do not update when change selectDate props

**Comment by christopherdro** [comment]
@zleast Were you able to find a resolution?

Calendar component is setup to properly update state when it's receives a change in props. 
I would double check your implementation.

Closing for now. Please reopen if its still an issue.
