### ISSUE TITLE
Cannot read property 'customStyle' of undefined

### ISSUE THREAD

**Issue by chrise86** [christopherdro/react-native-calendar#53]
Using version `0.7.0` when using the code from the example in Readme I get this error, which relates to `Day.js:33`

![simulator screen shot 16 jul 2016 12 49 04](https://cloud.githubusercontent.com/assets/616956/16894633/d0dd1f06-4b53-11e6-9bba-d4c523b9d6b9.png)

**Comment by chrise86** [comment]
When using `0.6.4` the styles seem a bit messed up:

![simulator screen shot 16 jul 2016 15 56 58](https://cloud.githubusercontent.com/assets/616956/16895438/056ca894-4b6e-11e6-9802-fda557134905.png)

**Comment by KGALLET** [comment]
@chrise86 hi, can you show your code in order to help you?

**Comment by chrise86** [comment]
I had to give up and try something else, so don't have the code anymore. However, I pretty much just copied the example code in the readme into a new (es6) component and as soon as I navigated to that component it crashed. If I find some time I'll try and replicate it and share the code.

**Comment by KGALLET** [comment]
@chrise86 I had the problem of style in 0.6.4 but I don't remember how I solved it. 
I could probably help you if you decide to try it one more time.

**Comment by ssomnoremac** [comment]
I had the `dayCircleStyle` error as well. I'm just running the example. I console.logged `this.props` within said function of `Day.js` and it's `undefined`. @KGALLET I would check that out.

**Comment by christopherdro** [comment]
Shouldn't be a problem in the latest version.

Please re-open if you see the issue come up.
