### ISSUE TITLE
Select date range

### ISSUE THREAD

**Issue by basequatro** [christopherdro/react-native-calendar#58]
Is possible to select a date range?

**Comment by KGALLET** [comment]
I think no

**Comment by hejiaji** [comment]
What does the "I think so" mean? @KGALLET

**Comment by vincentfretin** [comment]
@hejiaji He said "I think no", not "so". In better English, he wanted to say "I don't think so" ;)

**Comment by hejiaji** [comment]
Wow, haha, thanks @vincentfretin
