### ISSUE TITLE
Edit Multiple Style of calendar view using customStyle props

### ISSUE THREAD

**Issue by vykumar** [christopherdro/react-native-calendar#59]
customStyle={({ eventIndicator: { backgroundColor: '#ff0000' } },
          { eventIndicatorFiller: { marginTop: 10, width: 10 } },
          { currentDayCircle: { backgroundColor: 'black' } })}

when I used above code, It is only editing currentDayCircle not all three. 

can you please tell me how to edit multiple style at once by using customStyle props.

**Comment by christopherdro** [comment]
The `customStyle` prop expects a plain object with properties that map to the available custom styles.

Take a look at the documentation here: https://github.com/christopherdro/react-native-calendar#available-custom-styles.

Your snippet above has some syntax issues. Should look something like this...
```js

const customStyle = {
  eventIndicator: { backgroundColor: '#ff0000' },
  eventIndicatorFiller: { marginTop: 10, width: 10 }, 
  currentDayCircle: { backgroundColor: 'black' } 
}

<Calendar customStyle={customStyle} />
```
