### ISSUE TITLE
Add support for hasEventDaySelectedCircle?

### ISSUE THREAD

**Issue by nodegin** [christopherdro/react-native-calendar#61]
Hello, thanks for this amazing library first of all.

I'm just wondering is there any style configuration to styling the circle of event days, but only for selected state.

Currently if I use `hasEventCircle` the circle will turns into the defined background color even there already has an indicator below.

So I'm looking for something like `hasEventDaySelectedCircle` or `selectedEventIndicator`, thank you very much.

**Comment by christopherdro** [comment]
@nodegin It appears this isn't currently customizable but should be pretty straightforward to add it.

Would you like to give it a shot and maybe submit a PR with the change?

**Comment by hejiaji** [comment]
If i got this right, @nodegin you want a style configuration for event days but only for selected one? why not using selectedDayCircle instead? correct me if i'm wrong.... or you want is specific circle just for event day which is selected?  different from non-event selected day. which will be implemented in selectedDayCircle...   @christopherdro if i'm right, i can help with a PR

**Comment by hejiaji** [comment]
#85

**Comment by nodegin** [comment]
@hejiaji yes that's correct. (style configuration for event days but only for selected one)
