### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by surendharreddy** [christopherdro/react-native-calendar#67]
I have been testing this module on iPhone 6S, the date selection is pretty slow. 

Let me know if there are any tweaks that I could try to make it faster. 

Thanks.

**Comment by ronak301** [comment]
+1

**Comment by MosesEsan** [comment]
Try changing it to Release mode when you run it on your device
![screen shot 2016-09-26 at 3 27 58 pm](https://cloud.githubusercontent.com/assets/3628999/18848913/8a99097c-83fe-11e6-8f7a-8df4c264494b.png)
![screen shot 2016-09-26 at 3 28 17 pm](https://cloud.githubusercontent.com/assets/3628999/18848914/8a9d9e06-83fe-11e6-8b11-217319e5e81e.png)

**Comment by christopherdro** [comment]
Duplicate #67
