### ISSUE TITLE
Wrong start date on Android

### ISSUE THREAD

**Issue by dbuarque** [christopherdro/react-native-calendar#72]
Hey @christopherdro ,

I have tried to set a start date(2016-09-10T03:00:00.000Z) and it work very well on iOS, however on Android it changes the date that is visible on calendar showing 2 months ago. 

```
<Calendar
          scrollEnabled={true}
          showControls={true}
          titleFormat={'MMMM'}
          dayHeadings={dayLabels}
          monthNames={monthLabels}
          prevButtonText={<Icon name="ios-arrow-back-outline" color="white" size={30} />}
          nextButtonText={<Icon name="ios-arrow-forward-outline" color="white" size={30} />}
          onDateSelect={(date) => handleDateSelection(date)}
          onTouchPrev={this.onTouchPrev}
          onTouchNext={this.onTouchNext}
          onSwipePrev={this.onSwipePrev}
          onSwipeNext={this.onSwipeNext}
          eventDates={eventDates}
          startDate={startDate}
          customStyle={calendarStyle}
          weekStart={0}
        />
```

<img width="561" alt="screen shot 2016-10-20 at 11 38 40" src="https://cloud.githubusercontent.com/assets/559571/19562391/ea271aea-96ba-11e6-87f2-ccc3e913d40a.png">

**Comment by christopherdro** [comment]
Just merged this that might fix the issue.
https://github.com/christopherdro/react-native-calendar/pull/68

Can you give it a try?

**Comment by bmelnychuk** [comment]
Still does not work

**Comment by sagark1510** [comment]
I am also facing the same issue... Any solution?

**Comment by dbuarque** [comment]
I have notice that if I click on any day it get the right date

**Comment by dbuarque** [comment]
Hi @christopherdro  it's working!

```
    "react-native-calendar": "christopherdro/react-native-calendar#master",
```

We just have to use the master branch because it isn't released yet

**Comment by christopherdro** [comment]
Nice. I'll do a new release this weekend.

**Comment by christopherdro** [comment]
https://github.com/christopherdro/react-native-calendar/releases/tag/v0.9.0
