### ISSUE TITLE
Can we remove usingEvents prop in Day.js?

### ISSUE THREAD

**Issue by hejiaji** [christopherdro/react-native-calendar#75]
For example:

if there is no events in 2016 October, the eventIndicatorFiller view won't be there, the height of day is 65, then if we change date to 2016 Nov, let's say there are events in this month, then the eventIndicatorFiller view will be render , the height of day will be 70 (if the eventIndicatorFiller view height is 5), it will cause page flash for row height change. 

Can we remove the usingEvents props? instead we can always keep the view there, we can show the indicator based on the events, but i don't want the page shake

**Comment by hejiaji** [comment]
@christopherdro

**Comment by christopherdro** [comment]
Mind submitting a PR with these changes?

**Comment by hejiaji** [comment]
@christopherdro no problem, have done it.  please check out [PR](https://github.com/christopherdro/react-native-calendar/pull/76)

**Comment by christopherdro** [comment]
Updated via https://github.com/christopherdro/react-native-calendar/pull/77
