### ISSUE TITLE
Prev month and next month

### ISSUE THREAD

**Issue by challenger532** [christopherdro/react-native-calendar#78]
Hello, 

Instead of showing the words 'prev' and 'next', it's better to show the name and previous month and next month, example:
If current displayed month is 'Nov', show 'Oct' on the left and 'Dec' on the right.

Thanks,

**Comment by christopherdro** [comment]
You can do this by using props `prevButtonText` and `nextButtonText` or create your own menu bar and disable the built in one by setting the prop `showControls` to false.
