### ISSUE TITLE
Disable past dates

### ISSUE THREAD

**Issue by adrianha** [christopherdro/react-native-calendar#79]
Hi,
Thank you for this great library 👍  !
I've customized this library to disable past dates by passing property called `pastDisabled`.
What do you think about this customization? I can send pull request if you dont mind.

Thank you

**Comment by dinithminura** [comment]
I think that property should be there. 1+

**Comment by christopherdro** [comment]
@adrianha  I'd be more than happy to review a PR.

**Comment by christopherdro** [comment]
https://github.com/christopherdro/react-native-calendar/pull/107

**Comment by basanthalluri** [comment]
Hi Floks, How to disable the Past dates in this Calendar Module?

**Comment by Kim-Andersen** [comment]
Maybe _minDate_ and _maxDate_ props would be more flexible to achieve this plus other scenarios?
