### ISSUE TITLE
Change year

### ISSUE THREAD

**Issue by nikolal** [christopherdro/react-native-calendar#89]
I don't know if this is possible but is there a way to change year on click or swipe? 
If I want to allow users to easily add dates from 50 years ago?

I can't seem to find this fuctionality.

**Comment by hejiaji** [comment]
Interesting proposal, i will try to implement this when i'm free, or can you try to put a pull request about this?

**Comment by nikolal** [comment]
I am very busy at the moment with my other work.
I will check this when I get more time.

**Comment by christopherdro** [comment]
@nikolal This is not currently supported and am not sure we plan on supporting this anytime soon.
